# Generated by Django 5.0.6 on 2026-08-14
# This is a clean initial migration

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import LAND_USE_PARCELS.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(db_index=True, help_text='Unique parcel identifier', max_length=50, unique=True)),
                ('parcel_name', models.CharField(blank=True, help_text='Parcel name or description', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude in decimal degrees', max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude in decimal degrees', max_digits=11, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('section', models.CharField(blank=True, help_text='Section or neighborhood', max_length=100)),
                ('section_number', models.CharField(blank=True, help_text='Section number', max_length=50)),
                ('street', models.CharField(blank=True, help_text='Street address', max_length=255)),
                ('master_plan_zone', models.CharField(blank=True, help_text='Master plan zone designation', max_length=100)),
                ('field_land_use', models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('RESIDENTIAL', 'Residential'), ('INSTITUTIONAL', 'Institutional'), ('RECREATIONAL', 'Recreational'), ('TRANSPORTATION', 'Transportation'), ('UTILITY', 'Utility'), ('VACANT', 'Vacant'), ('OTHER', 'Other')], help_text='Current land use observed in the field', max_length=50)),
                ('field_structure_status', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DILAPIDATED', 'Dilapidated'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('VACANT', 'Vacant'), ('DEMOLISHED', 'Demolished'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='Current structure status observed in the field', max_length=50)),
                ('field_notes', models.TextField(blank=True, help_text='Additional field observation notes')),
                ('field_photo', models.ImageField(blank=True, help_text='Field photo of the parcel', null=True, upload_to=LAND_USE_PARCELS.models.rename_photo)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this parcel has been field-verified')),
                ('date_visited', models.DateField(blank=True, help_text='Date of field visit', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this parcel record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this parcel record was last updated')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='User who last edited this parcel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_parcels', to='auth.user')),
            ],
            options={
                'verbose_name': 'Parcel',
                'verbose_name_plural': 'Parcels',
                'ordering': ['parcel_id'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Six-digit numeric code', max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='auth.user')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedParcelLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Layer name', max_length=255)),
                ('geojson', models.JSONField(help_text='GeoJSON data for the layer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_layers', to='auth.user')),
            ],
            options={
                'verbose_name': 'Saved Layer',
                'verbose_name_plural': 'Saved Layers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(help_text='Display order within the parcel')),
                ('structure_type', models.CharField(choices=[('RESIDENTIAL', 'Residential Building'), ('COMMERCIAL', 'Commercial Building'), ('INDUSTRIAL', 'Industrial Building'), ('INSTITUTIONAL', 'Institutional Building'), ('AGRICULTURAL', 'Agricultural Structure'), ('STORAGE', 'Storage Structure'), ('GARAGE', 'Garage'), ('SHED', 'Shed'), ('TEMPORARY', 'Temporary Structure'), ('OTHER', 'Other')], help_text='Type of structure', max_length=50)),
                ('storeys', models.PositiveIntegerField(blank=True, help_text='Number of storeys', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('condition', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DILAPIDATED', 'Dilapidated'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('VACANT', 'Vacant'), ('DEMOLISHED', 'Demolished'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='Condition of the structure', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the structure')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the structure', null=True, upload_to=LAND_USE_PARCELS.models.rename_structure_photo)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='LAND_USE_PARCELS.parcel')),
            ],
            options={
                'verbose_name': 'Structure',
                'verbose_name_plural': 'Structures',
                'ordering': ['sequence'],
            },
        ),
    ]