# Generated by Django 5.0.6 on 2026-07-22 05:24

import LAND_USE_PARCELS.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('parcel_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('master_plan_zone', models.CharField(blank=True, max_length=100, null=True)),
                ('field_land_use', models.CharField(blank=True, choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('MIX', 'Mixed-Use'), ('AGR', 'Agriculture'), ('VAC', 'Vacant'), ('WET', 'Wetland')], max_length=3, null=True)),
                ('field_structure_status', models.CharField(blank=True, choices=[('COM', 'Complete'), ('UC', 'Under Construction'), ('UN', 'Uncompleted/Roofed'), ('COL', 'Collapsed'), ('NONE', 'No Structure')], max_length=4, null=True)),
                ('field_photo', models.ImageField(blank=True, null=True, upload_to=LAND_USE_PARCELS.models.rename_photo)),
                ('field_notes', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_visited', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
