# Generated by Django 5.0.6 on 2026-08-18 11:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LAND_USE_PARCELS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='PostGIS point geometry', null=True, srid=4326),
        ),
    ]
# root@srv-d9t2vqugekts73cln06g-79bf94b957-gqbxl:/app# 