# Generated by Django 5.0.6 on 2026-08-03 19:49

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAND_USE_PARCELS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='parcel',
            name='parcel_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='parcel',
            name='war_office_easting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='war_office_northing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_visited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_land_use',
            field=models.CharField(blank=True, choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('MIX', 'Mixed-Use'), ('AGR', 'Agriculture'), ('VAC', 'Vacant'), ('WET', 'Wetland')], default='VAC', max_length=3),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_structure_status',
            field=models.CharField(blank=True, choices=[('COM', 'Complete'), ('UC', 'Under Construction'), ('UN', 'Uncompleted/Roofed'), ('COL', 'Collapsed'), ('NONE', 'No Structure')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='master_plan_zone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
