# Generated by Django 5.0.6 on 2026-08-03 20:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAND_USE_PARCELS', '0002_parcel_last_edited_by_parcel_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='field_land_use',
            field=models.CharField(blank=True, choices=[('RES', 'Residential'), ('COM', 'Commercial'), ('MIX', 'Mixed-Use'), ('AGR', 'Agriculture'), ('VAC', 'Vacant'), ('WET', 'Wetland')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_structure_status',
            field=models.CharField(blank=True, choices=[('COM', 'Complete'), ('UC', 'Under Construction'), ('UN', 'Uncompleted/Roofed'), ('COL', 'Collapsed'), ('NONE', 'No Structure')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='latitude',
            field=models.FloatField(blank=True, help_text='WGS84 latitude in decimal degrees (EPSG:4326)', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Parcel location in WGS84 (EPSG:4326)', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='longitude',
            field=models.FloatField(blank=True, help_text='WGS84 longitude in decimal degrees (EPSG:4326)', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='master_plan_zone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='street',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='war_office_easting',
            field=models.FloatField(blank=True, help_text='Ghana War Office / Ghana National Grid Easting (metres)', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='war_office_northing',
            field=models.FloatField(blank=True, help_text='Ghana War Office / Ghana National Grid Northing (metres)', null=True),
        ),
    ]
