# Generated by Django 5.0.6 on 2026-08-03 23:07

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAND_USE_PARCELS', '0003_alter_parcel_field_land_use_alter_parcel_field_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Parcel location in WGS84 (EPSG:4326).', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='master_plan_zone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='street',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='war_office_easting',
            field=models.FloatField(blank=True, help_text='Ghana War Office / Ghana National Grid Easting in metres.', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='war_office_northing',
            field=models.FloatField(blank=True, help_text='Ghana War Office / Ghana National Grid Northing in metres.', null=True),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['user', 'is_used', '-created_at'], name='LAND_USE_PA_user_id_07b4ae_idx'),
        ),
    ]
