# Generated by Django 5.0.6 on 2026-08-05 03:38

import LAND_USE_PARCELS.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAND_USE_PARCELS', '0005_parcel_section_parcel_section_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='section',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='section_number',
            field=models.CharField(blank='', default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('structure_type', models.CharField(choices=[('SINGLE_ROOM', 'Single room'), ('SELF_CONTAINED', 'Self-contained'), ('SEMI_DETACHED', 'Semi-detached'), ('DETACHED', 'Detached'), ('COMPOUND', 'Compound house'), ('APARTMENT', 'Flat / apartment'), ('SHOP', 'Shop / kiosk'), ('OTHER', 'Other')], max_length=20)),
                ('storeys', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, choices=[('COM', 'Complete'), ('UC', 'Under Construction'), ('UN', 'Uncompleted/Roofed'), ('COL', 'Collapsed'), ('NONE', 'No Structure')], default='', max_length=4)),
                ('notes', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=LAND_USE_PARCELS.models.rename_structure_photo)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='LAND_USE_PARCELS.parcel')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='structure',
            constraint=models.UniqueConstraint(fields=('parcel', 'sequence'), name='unique_structure_sequence_per_parcel'),
        ),
    ]
