# Generated by Django 5.0.6 on 2026-08-14 15:47

import LAND_USE_PARCELS.models
import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAND_USE_PARCELS', '0007_savedparcellayer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Code', 'verbose_name_plural': 'OTP Codes'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['parcel_id'], 'verbose_name': 'Parcel', 'verbose_name_plural': 'Parcels'},
        ),
        migrations.AlterModelOptions(
            name='savedparcellayer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saved Layer', 'verbose_name_plural': 'Saved Layers'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['sequence'], 'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.RemoveConstraint(
            model_name='structure',
            name='unique_structure_sequence_per_parcel',
        ),
        migrations.RemoveIndex(
            model_name='otpcode',
            name='LAND_USE_PA_user_id_07b4ae_idx',
        ),
        migrations.RenameField(
            model_name='structure',
            old_name='recorded_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='war_office_easting',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='war_office_northing',
        ),
        migrations.AddField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this parcel record was created'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this parcel record was last updated'),
        ),
        migrations.AddField(
            model_name='savedparcellayer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(help_text='Six-digit numeric code', max_length=6),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False, help_text='Whether this code has been used'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_visited',
            field=models.DateField(blank=True, help_text='Date of field visit', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_land_use',
            field=models.CharField(blank=True, choices=[('AGRICULTURE', 'Agriculture'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('RESIDENTIAL', 'Residential'), ('INSTITUTIONAL', 'Institutional'), ('RECREATIONAL', 'Recreational'), ('TRANSPORTATION', 'Transportation'), ('UTILITY', 'Utility'), ('VACANT', 'Vacant'), ('OTHER', 'Other')], help_text='Current land use observed in the field', max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_notes',
            field=models.TextField(blank=True, help_text='Additional field observation notes'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_photo',
            field=models.ImageField(blank=True, help_text='Field photo of the parcel', null=True, upload_to=LAND_USE_PARCELS.models.rename_photo),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='field_structure_status',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DILAPIDATED', 'Dilapidated'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('VACANT', 'Vacant'), ('DEMOLISHED', 'Demolished'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='Current structure status observed in the field', max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this parcel has been field-verified'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='User who last edited this parcel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude in decimal degrees', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='PostGIS point geometry', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude in decimal degrees', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='master_plan_zone',
            field=models.CharField(blank=True, help_text='Master plan zone designation', max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(db_index=True, help_text='Unique parcel identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_name',
            field=models.CharField(blank=True, help_text='Parcel name or description', max_length=255),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='section',
            field=models.CharField(blank=True, help_text='Section or neighborhood', max_length=100),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='section_number',
            field=models.CharField(blank=True, help_text='Section number', max_length=50),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='street',
            field=models.CharField(blank=True, help_text='Street address', max_length=255),
        ),
        migrations.AlterField(
            model_name='savedparcellayer',
            name='geojson',
            field=models.JSONField(help_text='GeoJSON data for the layer'),
        ),
        migrations.AlterField(
            model_name='savedparcellayer',
            name='name',
            field=models.CharField(help_text='Layer name', max_length=255),
        ),
        migrations.AlterField(
            model_name='structure',
            name='condition',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DILAPIDATED', 'Dilapidated'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('VACANT', 'Vacant'), ('DEMOLISHED', 'Demolished'), ('NOT_APPLICABLE', 'Not Applicable')], help_text='Condition of the structure', max_length=50),
        ),
        migrations.AlterField(
            model_name='structure',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the structure'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the structure', null=True, upload_to=LAND_USE_PARCELS.models.rename_structure_photo),
        ),
        migrations.AlterField(
            model_name='structure',
            name='sequence',
            field=models.PositiveIntegerField(help_text='Display order within the parcel'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='storeys',
            field=models.PositiveIntegerField(blank=True, help_text='Number of storeys', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='structure',
            name='structure_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential Building'), ('COMMERCIAL', 'Commercial Building'), ('INDUSTRIAL', 'Industrial Building'), ('INSTITUTIONAL', 'Institutional Building'), ('AGRICULTURAL', 'Agricultural Structure'), ('STORAGE', 'Storage Structure'), ('GARAGE', 'Garage'), ('SHED', 'Shed'), ('TEMPORARY', 'Temporary Structure'), ('OTHER', 'Other')], help_text='Type of structure', max_length=50),
        ),
    ]
